# Generated by Django 4.0 on 2022-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=500)),
                ('production_company', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=150)),
                ('writer', models.CharField(max_length=150)),
                ('actor_1', models.CharField(max_length=150)),
                ('actor_2', models.CharField(max_length=150)),
                ('actor_3', models.CharField(max_length=150)),
            ],
        ),
    ]
