# Generated by Django 4.0 on 2022-01-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='fun_facts',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
