# Generated by Django 4.0 on 2022-01-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_fun_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='locations',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
